ALTER TYPE "PhotoCaptureType" ADD VALUE IF NOT EXISTS 'WALL_OVERVIEW';
ALTER TYPE "PhotoCaptureType" ADD VALUE IF NOT EXISTS 'FINDING_CONTEXT';
ALTER TYPE "PhotoCaptureType" ADD VALUE IF NOT EXISTS 'FINDING_CLOSE_UP';
ALTER TYPE "PhotoCaptureType" ADD VALUE IF NOT EXISTS 'SUPPORTING_ANGLE';
ALTER TYPE "PhotoCaptureType" ADD VALUE IF NOT EXISTS 'SCALE_REFERENCE';
ALTER TYPE "PhotoCaptureType" ADD VALUE IF NOT EXISTS 'SERIAL_OR_LABEL';
ALTER TYPE "PhotoCaptureType" ADD VALUE IF NOT EXISTS 'VIDEO_FRAME_SNAPSHOT';
ALTER TYPE "PhotoCaptureType" ADD VALUE IF NOT EXISTS 'OTHER';

ALTER TABLE "InspectionMedia"
  ADD COLUMN IF NOT EXISTS "captureSessionId" TEXT,
  ADD COLUMN IF NOT EXISTS "capturePolicyVersion" TEXT,
  ADD COLUMN IF NOT EXISTS "captureSummary" JSONB;

CREATE UNIQUE INDEX IF NOT EXISTS "InspectionMedia_captureSessionId_key"
  ON "InspectionMedia"("captureSessionId");
