-- Tenant isolation policies. GENERATED by scripts/generate-rls-policies.mjs
-- from the live foreign-key graph; regenerate rather than editing by hand.
--
-- Defense in depth. Every application-level organizationId filter stays exactly
-- as it is; these only mean a filter that is ever missed returns nothing
-- instead of another tenant's rows.
--
-- FAILS CLOSED. An unset app.organization_id matches nothing, so forgetting to
-- establish a tenant returns no rows rather than every row. The literal '*' is
-- the explicit system escape hatch, used by the handful of paths that genuinely
-- have no organization — boot-time recovery sweeps, the Cloudflare Stream
-- webhook, public report links before the share resolves, and account lookup by
-- email. Each is a named withSystemTenant() call in the application.
--
-- 8 tables are deliberately unpoliced:
--   AuthCredential — no foreign-key path to an organization
--   AuthPasswordResetToken — no foreign-key path to an organization
--   AuthRefreshToken — no foreign-key path to an organization
--   MobilePushDevice — no foreign-key path to an organization
--   UserProfile — no foreign-key path to an organization
--   WebhookEvent — no foreign-key path to an organization
--   _prisma_migrations — migration metadata
--   propertyware_sync_locks — no foreign-key path to an organization


-- The organization itself, matched on its own id.
alter table "Organization" enable row level security;
drop policy if exists tenant_isolation on "Organization";
create policy tenant_isolation on "Organization"
  using (
        current_setting('app.organization_id', true) = '*'
        or "id"::text = current_setting('app.organization_id', true)
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or "id"::text = current_setting('app.organization_id', true)
  );

-- Tables carrying organizationId directly.
alter table "AiProviderConfiguration" enable row level security;
drop policy if exists tenant_isolation on "AiProviderConfiguration";
create policy tenant_isolation on "AiProviderConfiguration"
  using (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  );
alter table "AiUsageEvent" enable row level security;
drop policy if exists tenant_isolation on "AiUsageEvent";
create policy tenant_isolation on "AiUsageEvent"
  using (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  );
alter table "AreaChecklistItem" enable row level security;
drop policy if exists tenant_isolation on "AreaChecklistItem";
create policy tenant_isolation on "AreaChecklistItem"
  using (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  );
alter table "AuditLog" enable row level security;
drop policy if exists tenant_isolation on "AuditLog";
create policy tenant_isolation on "AuditLog"
  using (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  );
alter table "Charge" enable row level security;
drop policy if exists tenant_isolation on "Charge";
create policy tenant_isolation on "Charge"
  using (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  );
alter table "ChargeRule" enable row level security;
drop policy if exists tenant_isolation on "ChargeRule";
create policy tenant_isolation on "ChargeRule"
  using (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  );
alter table "Inspection" enable row level security;
drop policy if exists tenant_isolation on "Inspection";
create policy tenant_isolation on "Inspection"
  using (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  );
alter table "InspectionComparison" enable row level security;
drop policy if exists tenant_isolation on "InspectionComparison";
create policy tenant_isolation on "InspectionComparison"
  using (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  );
alter table "InspectionMedia" enable row level security;
drop policy if exists tenant_isolation on "InspectionMedia";
create policy tenant_isolation on "InspectionMedia"
  using (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  );
alter table "InspectionPhoto" enable row level security;
drop policy if exists tenant_isolation on "InspectionPhoto";
create policy tenant_isolation on "InspectionPhoto"
  using (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  );
alter table "InspectionReportShare" enable row level security;
drop policy if exists tenant_isolation on "InspectionReportShare";
create policy tenant_isolation on "InspectionReportShare"
  using (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  );
alter table "OrganizationAiSettings" enable row level security;
drop policy if exists tenant_isolation on "OrganizationAiSettings";
create policy tenant_isolation on "OrganizationAiSettings"
  using (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  );
alter table "OrganizationMember" enable row level security;
drop policy if exists tenant_isolation on "OrganizationMember";
create policy tenant_isolation on "OrganizationMember"
  using (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  );
alter table "PetCandidate" enable row level security;
drop policy if exists tenant_isolation on "PetCandidate";
create policy tenant_isolation on "PetCandidate"
  using (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  );
alter table "PetObservation" enable row level security;
drop policy if exists tenant_isolation on "PetObservation";
create policy tenant_isolation on "PetObservation"
  using (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  );
alter table "Property" enable row level security;
drop policy if exists tenant_isolation on "Property";
create policy tenant_isolation on "Property"
  using (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  );
alter table "Role" enable row level security;
drop policy if exists tenant_isolation on "Role";
create policy tenant_isolation on "Role"
  using (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  );
alter table "UserRoleAssignment" enable row level security;
drop policy if exists tenant_isolation on "UserRoleAssignment";
create policy tenant_isolation on "UserRoleAssignment"
  using (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  );
alter table "propertyware_buildings" enable row level security;
drop policy if exists tenant_isolation on "propertyware_buildings";
create policy tenant_isolation on "propertyware_buildings"
  using (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  );
alter table "propertyware_leases" enable row level security;
drop policy if exists tenant_isolation on "propertyware_leases";
create policy tenant_isolation on "propertyware_leases"
  using (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  );
alter table "propertyware_owners" enable row level security;
drop policy if exists tenant_isolation on "propertyware_owners";
create policy tenant_isolation on "propertyware_owners"
  using (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  );
alter table "propertyware_portfolios" enable row level security;
drop policy if exists tenant_isolation on "propertyware_portfolios";
create policy tenant_isolation on "propertyware_portfolios"
  using (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  );
alter table "propertyware_sync_cursors" enable row level security;
drop policy if exists tenant_isolation on "propertyware_sync_cursors";
create policy tenant_isolation on "propertyware_sync_cursors"
  using (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  );
alter table "propertyware_sync_runs" enable row level security;
drop policy if exists tenant_isolation on "propertyware_sync_runs";
create policy tenant_isolation on "propertyware_sync_runs"
  using (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  );
alter table "propertyware_units" enable row level security;
drop policy if exists tenant_isolation on "propertyware_units";
create policy tenant_isolation on "propertyware_units"
  using (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or "organizationId"::text = current_setting('app.organization_id', true)
  );

-- Tables reached through foreign keys.

-- AiAnalysisJob -> InspectionMedia
alter table "AiAnalysisJob" enable row level security;
drop policy if exists tenant_isolation on "AiAnalysisJob";
create policy tenant_isolation on "AiAnalysisJob"
  using (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "InspectionMedia" p0
          where p0."id" = "AiAnalysisJob"."inspectionMediaId"
            and p0."organizationId"::text = current_setting('app.organization_id', true))
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "InspectionMedia" p0
          where p0."id" = "AiAnalysisJob"."inspectionMediaId"
            and p0."organizationId"::text = current_setting('app.organization_id', true))
  );

-- BaselineAreaCondition -> BaselineInspection -> Property
alter table "BaselineAreaCondition" enable row level security;
drop policy if exists tenant_isolation on "BaselineAreaCondition";
create policy tenant_isolation on "BaselineAreaCondition"
  using (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "BaselineInspection" p0
          where p0."id" = "BaselineAreaCondition"."baselineInspectionId"
            and exists (select 1 from "Property" p1
          where p1."id" = p0."propertyId"
            and p1."organizationId"::text = current_setting('app.organization_id', true)))
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "BaselineInspection" p0
          where p0."id" = "BaselineAreaCondition"."baselineInspectionId"
            and exists (select 1 from "Property" p1
          where p1."id" = p0."propertyId"
            and p1."organizationId"::text = current_setting('app.organization_id', true)))
  );

-- BaselineInspection -> Property
alter table "BaselineInspection" enable row level security;
drop policy if exists tenant_isolation on "BaselineInspection";
create policy tenant_isolation on "BaselineInspection"
  using (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "Property" p0
          where p0."id" = "BaselineInspection"."propertyId"
            and p0."organizationId"::text = current_setting('app.organization_id', true))
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "Property" p0
          where p0."id" = "BaselineInspection"."propertyId"
            and p0."organizationId"::text = current_setting('app.organization_id', true))
  );

-- BaselineMedia -> BaselineAreaCondition -> BaselineInspection -> Property
alter table "BaselineMedia" enable row level security;
drop policy if exists tenant_isolation on "BaselineMedia";
create policy tenant_isolation on "BaselineMedia"
  using (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "BaselineAreaCondition" p0
          where p0."id" = "BaselineMedia"."baselineAreaConditionId"
            and exists (select 1 from "BaselineInspection" p1
          where p1."id" = p0."baselineInspectionId"
            and exists (select 1 from "Property" p2
          where p2."id" = p1."propertyId"
            and p2."organizationId"::text = current_setting('app.organization_id', true))))
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "BaselineAreaCondition" p0
          where p0."id" = "BaselineMedia"."baselineAreaConditionId"
            and exists (select 1 from "BaselineInspection" p1
          where p1."id" = p0."baselineInspectionId"
            and exists (select 1 from "Property" p2
          where p2."id" = p1."propertyId"
            and p2."organizationId"::text = current_setting('app.organization_id', true))))
  );

-- FindingReview -> InspectionFinding -> InspectionMedia
alter table "FindingReview" enable row level security;
drop policy if exists tenant_isolation on "FindingReview";
create policy tenant_isolation on "FindingReview"
  using (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "InspectionFinding" p0
          where p0."id" = "FindingReview"."findingId"
            and exists (select 1 from "InspectionMedia" p1
          where p1."id" = p0."inspectionMediaId"
            and p1."organizationId"::text = current_setting('app.organization_id', true)))
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "InspectionFinding" p0
          where p0."id" = "FindingReview"."findingId"
            and exists (select 1 from "InspectionMedia" p1
          where p1."id" = p0."inspectionMediaId"
            and p1."organizationId"::text = current_setting('app.organization_id', true)))
  );

-- FloorPlanExtractionJob -> PropertyFloorPlan -> Property
alter table "FloorPlanExtractionJob" enable row level security;
drop policy if exists tenant_isolation on "FloorPlanExtractionJob";
create policy tenant_isolation on "FloorPlanExtractionJob"
  using (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "PropertyFloorPlan" p0
          where p0."id" = "FloorPlanExtractionJob"."floorPlanId"
            and exists (select 1 from "Property" p1
          where p1."id" = p0."propertyId"
            and p1."organizationId"::text = current_setting('app.organization_id', true)))
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "PropertyFloorPlan" p0
          where p0."id" = "FloorPlanExtractionJob"."floorPlanId"
            and exists (select 1 from "Property" p1
          where p1."id" = p0."propertyId"
            and p1."organizationId"::text = current_setting('app.organization_id', true)))
  );

-- InspectionArea -> Inspection
alter table "InspectionArea" enable row level security;
drop policy if exists tenant_isolation on "InspectionArea";
create policy tenant_isolation on "InspectionArea"
  using (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "Inspection" p0
          where p0."id" = "InspectionArea"."inspectionId"
            and p0."organizationId"::text = current_setting('app.organization_id', true))
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "Inspection" p0
          where p0."id" = "InspectionArea"."inspectionId"
            and p0."organizationId"::text = current_setting('app.organization_id', true))
  );

-- InspectionAreaComparison -> InspectionComparison
alter table "InspectionAreaComparison" enable row level security;
drop policy if exists tenant_isolation on "InspectionAreaComparison";
create policy tenant_isolation on "InspectionAreaComparison"
  using (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "InspectionComparison" p0
          where p0."id" = "InspectionAreaComparison"."comparisonId"
            and p0."organizationId"::text = current_setting('app.organization_id', true))
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "InspectionComparison" p0
          where p0."id" = "InspectionAreaComparison"."comparisonId"
            and p0."organizationId"::text = current_setting('app.organization_id', true))
  );

-- InspectionAreaStatusHistory -> InspectionArea -> Inspection
alter table "InspectionAreaStatusHistory" enable row level security;
drop policy if exists tenant_isolation on "InspectionAreaStatusHistory";
create policy tenant_isolation on "InspectionAreaStatusHistory"
  using (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "InspectionArea" p0
          where p0."id" = "InspectionAreaStatusHistory"."inspectionAreaId"
            and exists (select 1 from "Inspection" p1
          where p1."id" = p0."inspectionId"
            and p1."organizationId"::text = current_setting('app.organization_id', true)))
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "InspectionArea" p0
          where p0."id" = "InspectionAreaStatusHistory"."inspectionAreaId"
            and exists (select 1 from "Inspection" p1
          where p1."id" = p0."inspectionId"
            and p1."organizationId"::text = current_setting('app.organization_id', true)))
  );

-- InspectionAssignment -> Inspection
alter table "InspectionAssignment" enable row level security;
drop policy if exists tenant_isolation on "InspectionAssignment";
create policy tenant_isolation on "InspectionAssignment"
  using (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "Inspection" p0
          where p0."id" = "InspectionAssignment"."inspectionId"
            and p0."organizationId"::text = current_setting('app.organization_id', true))
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "Inspection" p0
          where p0."id" = "InspectionAssignment"."inspectionId"
            and p0."organizationId"::text = current_setting('app.organization_id', true))
  );

-- InspectionFinding -> InspectionMedia
alter table "InspectionFinding" enable row level security;
drop policy if exists tenant_isolation on "InspectionFinding";
create policy tenant_isolation on "InspectionFinding"
  using (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "InspectionMedia" p0
          where p0."id" = "InspectionFinding"."inspectionMediaId"
            and p0."organizationId"::text = current_setting('app.organization_id', true))
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "InspectionMedia" p0
          where p0."id" = "InspectionFinding"."inspectionMediaId"
            and p0."organizationId"::text = current_setting('app.organization_id', true))
  );

-- MediaProcessingEvent -> InspectionMedia
alter table "MediaProcessingEvent" enable row level security;
drop policy if exists tenant_isolation on "MediaProcessingEvent";
create policy tenant_isolation on "MediaProcessingEvent"
  using (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "InspectionMedia" p0
          where p0."id" = "MediaProcessingEvent"."inspectionMediaId"
            and p0."organizationId"::text = current_setting('app.organization_id', true))
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "InspectionMedia" p0
          where p0."id" = "MediaProcessingEvent"."inspectionMediaId"
            and p0."organizationId"::text = current_setting('app.organization_id', true))
  );

-- MediaUploadSession -> InspectionArea -> Inspection
alter table "MediaUploadSession" enable row level security;
drop policy if exists tenant_isolation on "MediaUploadSession";
create policy tenant_isolation on "MediaUploadSession"
  using (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "InspectionArea" p0
          where p0."id" = "MediaUploadSession"."inspectionAreaId"
            and exists (select 1 from "Inspection" p1
          where p1."id" = p0."inspectionId"
            and p1."organizationId"::text = current_setting('app.organization_id', true)))
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "InspectionArea" p0
          where p0."id" = "MediaUploadSession"."inspectionAreaId"
            and exists (select 1 from "Inspection" p1
          where p1."id" = p0."inspectionId"
            and p1."organizationId"::text = current_setting('app.organization_id', true)))
  );

-- PropertyArea -> Property
alter table "PropertyArea" enable row level security;
drop policy if exists tenant_isolation on "PropertyArea";
create policy tenant_isolation on "PropertyArea"
  using (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "Property" p0
          where p0."id" = "PropertyArea"."propertyId"
            and p0."organizationId"::text = current_setting('app.organization_id', true))
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "Property" p0
          where p0."id" = "PropertyArea"."propertyId"
            and p0."organizationId"::text = current_setting('app.organization_id', true))
  );

-- PropertyAreaAlias -> PropertyArea -> Property
alter table "PropertyAreaAlias" enable row level security;
drop policy if exists tenant_isolation on "PropertyAreaAlias";
create policy tenant_isolation on "PropertyAreaAlias"
  using (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "PropertyArea" p0
          where p0."id" = "PropertyAreaAlias"."propertyAreaId"
            and exists (select 1 from "Property" p1
          where p1."id" = p0."propertyId"
            and p1."organizationId"::text = current_setting('app.organization_id', true)))
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "PropertyArea" p0
          where p0."id" = "PropertyAreaAlias"."propertyAreaId"
            and exists (select 1 from "Property" p1
          where p1."id" = p0."propertyId"
            and p1."organizationId"::text = current_setting('app.organization_id', true)))
  );

-- PropertyFloor -> Property
alter table "PropertyFloor" enable row level security;
drop policy if exists tenant_isolation on "PropertyFloor";
create policy tenant_isolation on "PropertyFloor"
  using (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "Property" p0
          where p0."id" = "PropertyFloor"."propertyId"
            and p0."organizationId"::text = current_setting('app.organization_id', true))
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "Property" p0
          where p0."id" = "PropertyFloor"."propertyId"
            and p0."organizationId"::text = current_setting('app.organization_id', true))
  );

-- PropertyFloorPlan -> Property
alter table "PropertyFloorPlan" enable row level security;
drop policy if exists tenant_isolation on "PropertyFloorPlan";
create policy tenant_isolation on "PropertyFloorPlan"
  using (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "Property" p0
          where p0."id" = "PropertyFloorPlan"."propertyId"
            and p0."organizationId"::text = current_setting('app.organization_id', true))
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "Property" p0
          where p0."id" = "PropertyFloorPlan"."propertyId"
            and p0."organizationId"::text = current_setting('app.organization_id', true))
  );

-- TranscriptSegment -> TranscriptionJob -> InspectionMedia
alter table "TranscriptSegment" enable row level security;
drop policy if exists tenant_isolation on "TranscriptSegment";
create policy tenant_isolation on "TranscriptSegment"
  using (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "TranscriptionJob" p0
          where p0."id" = "TranscriptSegment"."transcriptionJobId"
            and exists (select 1 from "InspectionMedia" p1
          where p1."id" = p0."inspectionMediaId"
            and p1."organizationId"::text = current_setting('app.organization_id', true)))
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "TranscriptionJob" p0
          where p0."id" = "TranscriptSegment"."transcriptionJobId"
            and exists (select 1 from "InspectionMedia" p1
          where p1."id" = p0."inspectionMediaId"
            and p1."organizationId"::text = current_setting('app.organization_id', true)))
  );

-- TranscriptionJob -> InspectionMedia
alter table "TranscriptionJob" enable row level security;
drop policy if exists tenant_isolation on "TranscriptionJob";
create policy tenant_isolation on "TranscriptionJob"
  using (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "InspectionMedia" p0
          where p0."id" = "TranscriptionJob"."inspectionMediaId"
            and p0."organizationId"::text = current_setting('app.organization_id', true))
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "InspectionMedia" p0
          where p0."id" = "TranscriptionJob"."inspectionMediaId"
            and p0."organizationId"::text = current_setting('app.organization_id', true))
  );

-- propertyware_portfolio_owners -> propertyware_owners
alter table "propertyware_portfolio_owners" enable row level security;
drop policy if exists tenant_isolation on "propertyware_portfolio_owners";
create policy tenant_isolation on "propertyware_portfolio_owners"
  using (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "propertyware_owners" p0
          where p0."id" = "propertyware_portfolio_owners"."ownerId"
            and p0."organizationId"::text = current_setting('app.organization_id', true))
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "propertyware_owners" p0
          where p0."id" = "propertyware_portfolio_owners"."ownerId"
            and p0."organizationId"::text = current_setting('app.organization_id', true))
  );

-- propertyware_sync_errors -> propertyware_sync_runs
alter table "propertyware_sync_errors" enable row level security;
drop policy if exists tenant_isolation on "propertyware_sync_errors";
create policy tenant_isolation on "propertyware_sync_errors"
  using (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "propertyware_sync_runs" p0
          where p0."id" = "propertyware_sync_errors"."syncRunId"
            and p0."organizationId"::text = current_setting('app.organization_id', true))
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "propertyware_sync_runs" p0
          where p0."id" = "propertyware_sync_errors"."syncRunId"
            and p0."organizationId"::text = current_setting('app.organization_id', true))
  );

-- propertyware_sync_run_entities -> propertyware_sync_runs
alter table "propertyware_sync_run_entities" enable row level security;
drop policy if exists tenant_isolation on "propertyware_sync_run_entities";
create policy tenant_isolation on "propertyware_sync_run_entities"
  using (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "propertyware_sync_runs" p0
          where p0."id" = "propertyware_sync_run_entities"."syncRunId"
            and p0."organizationId"::text = current_setting('app.organization_id', true))
  )
  with check (
        current_setting('app.organization_id', true) = '*'
        or exists (select 1 from "propertyware_sync_runs" p0
          where p0."id" = "propertyware_sync_run_entities"."syncRunId"
            and p0."organizationId"::text = current_setting('app.organization_id', true))
  );
